dbt_transformations:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: gdelt
      # Needs to be updated
      host: 10.49.0.2
      port: 38123
      user: clickhouse
      password: 'clickhouse'
      secure: False