dbt_transformations:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: gdelt
      # Needs to be updated based upon deployment
      # host: gdelt-analytics.centralindia.cloudapp.azure.com
      host: 20.219.221.25
      port: 38123
      user: clickhouse
      password: 'clickhouse'
      secure: False