config: {}
dbt_transformations:
  outputs:
    dev:
      host: 10.49.0.2
      password: password
      port: 38123
      schema: gdelt
      secure: false
      threads: 3
      type: clickhouse
      user: admin
  target: dev
