global:
  checkNewVersion: false
  sendAnonymousUsage: false
serversTransport:
  insecureSkipVerify: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
  traefik:
    address: :8080

log:
  level: DEBUG
  filePath: /etc/traefik/debug.log

providers:
  docker: {}

  file:
    filename: /etc/traefik/traefikConfig.yml
    watch: true

  # kubernetesIngress: {}

  consulCatalog:
    endpoint:
      address: "127.0.0.1:8500"

  # consul:
  #   endpoints:
  #     - "127.0.0.1:9500"
api:
  insecure: true
  dashboard: true
  debug: false

tracing:
  jaeger: {}

certificatesResolvers:
  letsencrypt:
    # Enable ACME (Let's Encrypt): automatic SSL.
    acme:
      # Email address used for registration.
      #
      # Required
      #
      email: "example@gmail.com"

      # File or key used for certificates storage.
      #
      # Required
      #
      storage: "/etc/traefik/acme.json"

      # CA server to use.
      # Uncomment the line to use Let's Encrypt's staging server,
      # leave commented to go to prod.
      #
      # Optional
      # Default: "https://acme-v02.api.letsencrypt.org/directory"
      #
      caServer: "https://acme-v02.api.letsencrypt.org/directory"

      # Preferred chain to use.
      #
      # If the CA offers multiple certificate chains, prefer the chain with an issuer matching this Subject Common Name.
      # If no match, the default offered chain will be used.
      #
      # Optional
      # Default: ""
      #
      # preferredChain: 'ISRG Root X1'

      # KeyType to use.
      #
      # Optional
      # Default: "RSA4096"
      #
      # Available values : "EC256", "EC384", "RSA2048", "RSA4096", "RSA8192"
      #
      # keyType: RSA4096

      # Use a TLS-ALPN-01 ACME challenge.
      #
      # Optional (but recommended)
      #
      tlsChallenge: {}
      # Use a HTTP-01 ACME challenge.
      #
      # Optional
      #
      httpChallenge:
      # EntryPoint to use for the HTTP-01 challenges.
      #
      # Required
      #
        entryPoint: web
      # Use a DNS-01 ACME challenge rather than HTTP-01 challenge.
      # Note: mandatory for wildcard certificate generation.
      #
      # Optional
      #
      # dnsChallenge:
      # DNS provider used.
      #
      # Required
      #
      # provider: digitalocean
      # By default, the provider will verify the TXT DNS challenge record before letting ACME verify.
      # If delayBeforeCheck is greater than zero, this check is delayed for the configured duration in seconds.
      # Useful if internal networks block external DNS queries.
      #
      # Optional
      # Default: 0
      #
      # delayBeforeCheck: 0
      # Use following DNS servers to resolve the FQDN authority.
      #
      # Optional
      # Default: empty
      #
      # resolvers
      # - "1.1.1.1:53"
      # - "8.8.8.8:53"
      # Disable the DNS propagation checks before notifying ACME that the DNS challenge is ready.
      #
      # NOT RECOMMENDED:
      # Increase the risk of reaching Let's Encrypt's rate limits.
      #
      # Optional
      # Default: false
      #
      # disablePropagationCheck: true