
CREATE TABLE IF NOT EXISTS events(
    GLOBALEVENTID UInt64,
    SQLDATE Date,
    MonthYear UInt32,
    Year UInt32,
    FractionDate Nullable(Float64),
    Actor1Code Nullable(String),
    Actor1Name Nullable(String),
    Actor1CountryCode LowCardinality(Nullable(String)),
    Actor1KnownGroupCode LowCardinality(Nullable(String)),
    Actor1EthnicCode LowCardinality(Nullable(String)),
    Actor1Religion1Code LowCardinality(Nullable(String)),
    Actor1Religion2Code LowCardinality(Nullable(String)),
    Actor1Type1Code LowCardinality(Nullable(String)),
    Actor1Type2Code LowCardinality(Nullable(String)),
    Actor1Type3Code LowCardinality(Nullable(String)),
    Actor2Code Nullable(String),
    Actor2Name Nullable(String),
    Actor2CountryCode LowCardinality(Nullable(String)),
    Actor2KnownGroupCode LowCardinality(Nullable(String)),
    Actor2EthnicCode LowCardinality(Nullable(String)),
    Actor2Religion1Code LowCardinality(Nullable(String)),
    Actor2Religion2Code LowCardinality(Nullable(String)),
    Actor2Type1Code LowCardinality(Nullable(String)),
    Actor2Type2Code LowCardinality(Nullable(String)),
    Actor2Type3Code LowCardinality(Nullable(String)),
    IsRootEvent Nullable(UInt32),
    EventCode LowCardinality(Nullable(String)),
    EventBaseCode LowCardinality(Nullable(String)),
    EventRootCode LowCardinality(Nullable(String)),
    QuadClass Nullable(UInt32),
    GoldsteinScale Nullable(Float32),
    NumMentions Nullable(UInt32),
    NumSources Nullable(UInt32),
    NumArticles Nullable(UInt32),
    AvgTone Nullable(Float32),
    Actor1Geo_Type Nullable(String),
    Actor1Geo_FullName Nullable(String),
    Actor1Geo_CountryCode LowCardinality(Nullable(String)),
    Actor1Geo_ADM1Code LowCardinality(Nullable(String)),
    Actor1Geo_ADM2Code LowCardinality(Nullable(String)),
    Actor1Geo_Lat Nullable(Float32),
    Actor1Geo_Long Nullable(Float32),
    Actor1Geo_FeatureID Nullable(String),
    Actor2Geo_Type Nullable(String),
    Actor2Geo_FullName Nullable(String),
    Actor2Geo_CountryCode LowCardinality(Nullable(String)),
    Actor2Geo_ADM1Code LowCardinality(Nullable(String)),
    Actor2Geo_ADM2Code LowCardinality(Nullable(String)),
    Actor2Geo_Lat Nullable(Float32),
    Actor2Geo_Long Nullable(Float32),
    Actor2Geo_FeatureID Nullable(String),
    ActionGeo_Type Nullable(String),
    ActionGeo_FullName Nullable(String),
    ActionGeo_CountryCode LowCardinality(Nullable(String)),
    ActionGeo_ADM1Code LowCardinality(Nullable(String)),
    ActionGeo_ADM2Code LowCardinality(Nullable(String)),
    ActionGeo_Lat Nullable(Float32),
    ActionGeo_Long Nullable(Float32),
    ActionGeo_FeatureID Nullable(String),
    DATEADDED Nullable(DateTime),
    SOURCEURL Nullable(String)
    ) ENGINE = MergeTree()
    PARTITION BY toYYYYMM(SQLDATE)
    ORDER BY (SQLDATE, GLOBALEVENTID);

      